name: Complex Workflow

on:
  push:
    branches: [main]
    
  workflow_dispatch:
  
jobs:
  windows_job:
    runs-on:  windows-latest
    steps:
    - run: date
    
  ubuntu_job:
    runs-on:  ubuntu-latest
    steps:
    - run: date
  
  macos_job:
    runs-on:  macos-latest
    steps:
    - run:  date
    
  depends_job:
    runs-on:  ubuntu-latest
    needs:  [ windows_job, ubuntu_job, macos_job ]
    steps:
    - run:  date
  
  
